/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDlgAuthentication.java
 *
 * Created on 27 avr. 2011, 17:16:52
 */
package com.choranet.pos.forms;

import com.choranet.data.gui.JMessageDialog;
import com.choranet.data.gui.MessageInf;
import com.choranet.pos.config.JFrmConfig;
import javax.swing.UIManager;

/**
 *
 * @author mohamed
 */
public class JDlgAuthentication extends javax.swing.JFrame {

    boolean passToConfigPanel = false;

    /** Creates new form JDlgAuthentication */
    public JDlgAuthentication() {
        initComponents();
        setResizable(false);
        setLocation(500, 350);
        pack();
    }

    public boolean isPassToConfigPanel() {
        return passToConfigPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jcmdOK = new javax.swing.JButton();
        jcmdCancel = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        jLabel1.setText("   login");
        add(jLabel1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);

        jLabel2.setText("   Password");
        add(jLabel2);
        add(jPasswordField1);

        jcmdOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/choranet/images/button_ok.png"))); // NOI18N
        jcmdOK.setText(AppLocal.getIntString("Button.OK")); // NOI18N
        jcmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdOKActionPerformed(evt);
            }
        });
        add(jcmdOK);

        jcmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/choranet/images/button_cancel.png"))); // NOI18N
        jcmdCancel.setText(AppLocal.getIntString("Button.Cancel")); // NOI18N
        jcmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdCancelActionPerformed(evt);
            }
        });
        add(jcmdCancel);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdOKActionPerformed

        if (new String(jPasswordField1.getPassword()).equals("chora2010") &&
                new String(jTextField1.getText()).equals("admin")) {
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {

                    AppConfig config = new AppConfig();
                    config.load();

                    // Set the look and feel.
                    try {
                        UIManager.setLookAndFeel(config.getProperty("swing.defaultlaf"));
                        new JFrmConfig(config).setVisible(true);
                    } catch (Exception e) {
                    }
                }
            });
            dispose();
        } else {
            JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_WARNING,
                    AppLocal.getIntString("message.BadPassword")));
        }
}//GEN-LAST:event_jcmdOKActionPerformed

    private void jcmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdCancelActionPerformed

        System.exit(0);
}//GEN-LAST:event_jcmdCancelActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jcmdCancel;
    private javax.swing.JButton jcmdOK;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AppConfig config = new AppConfig();
                config.load();
                try {
                    UIManager.setLookAndFeel(config.getProperty("swing.defaultlaf"));
                    JDlgAuthentication dlgAuthentication = new JDlgAuthentication();
                    dlgAuthentication.setVisible(true);
                } catch (Exception e) {
                }

            }
        });
    }
}
